<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MediMind.Application</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MediMind.Domain\MediMind.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- CQRS + Mediator -->
    <PackageReference Include="MediatR" Version="12.*" />
    <!-- Validation pipeline -->
    <PackageReference Include="FluentValidation" Version="11.*" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.*" />
    <!-- Object mapping -->
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <!-- Logging abstraction -->
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.*" />
    <!-- DI abstractions -->
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.*" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="10.*" />
    <PackageReference Include="QuestPDF" Version="2024.*" />
  </ItemGroup>

</Project>
