// <auto-generated />
using System;
using System.Collections.Generic;
using MediMind.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MediMind.Infrastructure.Migrations
{
    [DbContext(typeof(MediMindDbContext))]
    [Migration("20260410045656_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediMind.Domain.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date")
                        .HasColumnName("appointment_date");

                    b.Property<TimeOnly>("AppointmentTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("appointment_time");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<Guid?>("ApprovedByAdminId")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_admin_id");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("booking_date");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("cancelled_by");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("center_id");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_in_time");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("check_out_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("duration_minutes");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("ReasonForVisit")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason_for_visit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Symptoms")
                        .HasColumnType("text")
                        .HasColumnName("symptoms");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_appointments");

                    b.HasIndex("ApprovedByAdminId")
                        .HasDatabaseName("i_x_appointments_approved_by_admin_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_appointments_status");

                    b.HasIndex("CenterId", "AppointmentDate")
                        .HasDatabaseName("i_x_appointments_center_id_appointment_date");

                    b.HasIndex("DoctorId", "AppointmentDate")
                        .HasDatabaseName("i_x_appointments_doctor_id_appointment_date");

                    b.HasIndex("PatientId", "AppointmentDate")
                        .HasDatabaseName("i_x_appointments_patient_id_appointment_date");

                    b.HasIndex("DoctorId", "CenterId", "AppointmentDate", "AppointmentTime")
                        .IsUnique()
                        .HasDatabaseName("idx_appointments_no_double_booking");

                    b.ToTable("appointments", null, t =>
                        {
                            t.HasCheckConstraint("ck_duration_minutes", "duration_minutes IN (15, 30, 45, 60)");
                        });
                });

            modelBuilder.Entity("MediMind.Domain.Entities.DoctorHealthcareCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("center_id");

                    b.Property<decimal>("ConsultationFee")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("consultation_fee");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateOnly>("JoinedDate")
                        .HasColumnType("date")
                        .HasColumnName("joined_date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_doctor_healthcare_centers");

                    b.HasIndex("CenterId")
                        .HasDatabaseName("i_x_doctor_healthcare_centers_center_id");

                    b.HasIndex("DoctorId", "CenterId")
                        .IsUnique()
                        .HasDatabaseName("i_x_doctor_healthcare_centers_doctor_id_center_id");

                    b.ToTable("doctor_healthcare_centers", null, t =>
                        {
                            t.HasCheckConstraint("ck_consultation_fee", "consultation_fee > 0");
                        });
                });

            modelBuilder.Entity("MediMind.Domain.Entities.DoctorSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<TimeOnly?>("BreakEnd")
                        .HasColumnType("time without time zone")
                        .HasColumnName("break_end");

                    b.Property<TimeOnly?>("BreakStart")
                        .HasColumnType("time without time zone")
                        .HasColumnName("break_start");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("SlotDuration")
                        .HasColumnType("integer")
                        .HasColumnName("slot_duration");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<List<string>>("WorkingDays")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("working_days");

                    b.HasKey("Id")
                        .HasName("p_k_doctor_schedules");

                    b.HasIndex("CenterId")
                        .HasDatabaseName("i_x_doctor_schedules_center_id");

                    b.HasIndex("DoctorId", "CenterId")
                        .IsUnique()
                        .HasDatabaseName("i_x_doctor_schedules_doctor_id_center_id");

                    b.ToTable("doctor_schedules", null, t =>
                        {
                            t.HasCheckConstraint("ck_break_times", "break_end > break_start OR break_start IS NULL");

                            t.HasCheckConstraint("ck_schedule_times", "end_time > start_time");
                        });
                });

            modelBuilder.Entity("MediMind.Domain.Entities.HealthPrediction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("prediction_id");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("confidence");

                    b.Property<Dictionary<string, List<string>>>("ContributingFactors")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contributing_factors");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CvdCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cvd_category");

                    b.Property<decimal>("CvdRisk")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("cvd_risk");

                    b.Property<int>("DataPointsUsed")
                        .HasColumnType("integer")
                        .HasColumnName("data_points_used");

                    b.Property<string>("DiabetesCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("diabetes_category");

                    b.Property<decimal>("DiabetesRisk")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("diabetes_risk");

                    b.Property<string>("HypertensionCategory")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("hypertension_category");

                    b.Property<decimal>("HypertensionRisk")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("hypertension_risk");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("model_version");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateOnly>("PredictionDate")
                        .HasColumnType("date")
                        .HasColumnName("prediction_date");

                    b.Property<TimeOnly>("PredictionTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("prediction_time");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recommendations");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_health_predictions");

                    b.HasIndex("PatientId", "PredictionDate")
                        .HasDatabaseName("i_x_health_predictions_patient_id_prediction_date");

                    b.ToTable("health_predictions", null, t =>
                        {
                            t.HasCheckConstraint("ck_data_points", "data_points_used > 0");
                        });
                });

            modelBuilder.Entity("MediMind.Domain.Entities.HealthPredictionRecord", b =>
                {
                    b.Property<Guid>("PredictionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prediction_id");

                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.HasKey("PredictionId", "RecordId")
                        .HasName("p_k_health_prediction_records");

                    b.HasIndex("RecordId")
                        .HasDatabaseName("i_x_health_prediction_records_record_id");

                    b.HasIndex("PredictionId", "RecordId")
                        .IsUnique()
                        .HasDatabaseName("i_x_health_prediction_records_prediction_id_record_id");

                    b.ToTable("health_prediction_records", (string)null);
                });

            modelBuilder.Entity("MediMind.Domain.Entities.HealthRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DiastolicBp")
                        .HasColumnType("integer")
                        .HasColumnName("diastolic_bp");

                    b.Property<decimal?>("GlucoseLevel")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("glucose_level");

                    b.Property<int?>("HeartRate")
                        .HasColumnType("integer")
                        .HasColumnName("heart_rate");

                    b.Property<decimal?>("Height")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("height");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("OxygenSaturation")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateOnly>("RecordDate")
                        .HasColumnType("date")
                        .HasColumnName("record_date");

                    b.Property<TimeOnly>("RecordTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("record_time");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("patient")
                        .HasColumnName("recorded_by");

                    b.Property<int?>("RespiratoryRate")
                        .HasColumnType("integer")
                        .HasColumnName("respiratory_rate");

                    b.Property<int?>("SystolicBp")
                        .HasColumnType("integer")
                        .HasColumnName("systolic_bp");

                    b.Property<decimal?>("Temperature")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("temperature");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("p_k_health_records");

                    b.HasIndex("PatientId", "RecordDate")
                        .HasDatabaseName("i_x_health_records_patient_id_record_date");

                    b.ToTable("health_records", null, t =>
                        {
                            t.HasCheckConstraint("ck_bp_relation", "systolic_bp > diastolic_bp OR systolic_bp IS NULL OR diastolic_bp IS NULL");

                            t.HasCheckConstraint("ck_diastolic_bp", "diastolic_bp BETWEEN 40 AND 150 OR diastolic_bp IS NULL");

                            t.HasCheckConstraint("ck_glucose", "glucose_level BETWEEN 30 AND 600 OR glucose_level IS NULL");

                            t.HasCheckConstraint("ck_heart_rate", "heart_rate BETWEEN 30 AND 250 OR heart_rate IS NULL");

                            t.HasCheckConstraint("ck_systolic_bp", "systolic_bp BETWEEN 70 AND 250 OR systolic_bp IS NULL");

                            t.HasCheckConstraint("ck_temperature", "temperature BETWEEN 35 AND 43 OR temperature IS NULL");
                        });
                });

            modelBuilder.Entity("MediMind.Domain.Entities.HealthcareCenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("center_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("address");

                    b.Property<int>("AdvanceBookingDays")
                        .HasColumnType("integer")
                        .HasColumnName("advance_booking_days");

                    b.Property<bool>("AutoApproveAppointments")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_approve_appointments");

                    b.Property<int>("CancellationHours")
                        .HasColumnType("integer")
                        .HasColumnName("cancellation_hours");

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("center_name");

                    b.Property<string>("CenterType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("center_type");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitude");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("license_number");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitude");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("region");

                    b.PrimitiveCollection<List<string>>("ServicesOffered")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("services_offered");

                    b.Property<int>("SlotDurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("slot_duration_minutes");

                    b.PrimitiveCollection<List<string>>("Specializations")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("specializations");

                    b.Property<DateOnly?>("SubscriptionEndDate")
                        .HasColumnType("date")
                        .HasColumnName("subscription_end_date");

                    b.Property<DateOnly?>("SubscriptionStartDate")
                        .HasColumnType("date")
                        .HasColumnName("subscription_start_date");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("subscription_status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Dictionary<string, string>>("WorkingHours")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("working_hours");

                    b.HasKey("Id")
                        .HasName("p_k_healthcare_centers");

                    b.HasIndex("LicenseNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_healthcare_centers_license_number");

                    b.HasIndex("SubscriptionStatus")
                        .HasDatabaseName("i_x_healthcare_centers_subscription_status");

                    b.HasIndex("City", "Region")
                        .HasDatabaseName("i_x_healthcare_centers_city_region");

                    b.ToTable("healthcare_centers", null, t =>
                        {
                            t.HasCheckConstraint("ck_advance_booking", "advance_booking_days BETWEEN 1 AND 90");

                            t.HasCheckConstraint("ck_slot_duration", "slot_duration_minutes IN (15, 30, 45, 60)");
                        });
                });

            modelBuilder.Entity("MediMind.Domain.Entities.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<string>("ChapaTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("chapa_transaction_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_date");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("payment_method");

                    b.Property<string>("PaymentRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("payment_ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_payments");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("i_x_payments_appointment_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("i_x_payments_patient_id");

                    b.HasIndex("PaymentRef")
                        .IsUnique()
                        .HasDatabaseName("i_x_payments_payment_ref");

                    b.HasIndex("Status")
                        .HasDatabaseName("i_x_payments_status");

                    b.ToTable("payments", null, t =>
                        {
                            t.HasCheckConstraint("ck_payment_amount", "amount > 0");
                        });
                });

            modelBuilder.Entity("MediMind.Domain.Entities.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("prescription_id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("center_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("diagnosis");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<DateOnly?>("ExpiryDate")
                        .HasColumnType("date")
                        .HasColumnName("expiry_date");

                    b.Property<string>("FollowUpInstructions")
                        .HasColumnType("text")
                        .HasColumnName("follow_up_instructions");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date")
                        .HasColumnName("issue_date");

                    b.PrimitiveCollection<List<string>>("LabTests")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("lab_tests");

                    b.Property<string>("Medications")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("medications");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<string>("PrescriptionUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("prescription_url");

                    b.Property<string>("QrCode")
                        .HasColumnType("text")
                        .HasColumnName("qr_code");

                    b.Property<string>("SpecialInstructions")
                        .HasColumnType("text")
                        .HasColumnName("special_instructions");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_prescriptions");

                    b.HasIndex("AppointmentId")
                        .HasDatabaseName("i_x_prescriptions_appointment_id");

                    b.HasIndex("CenterId")
                        .HasDatabaseName("i_x_prescriptions_center_id");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("i_x_prescriptions_doctor_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("i_x_prescriptions_patient_id");

                    b.ToTable("prescriptions", null, t =>
                        {
                            t.HasCheckConstraint("ck_expiry_date", "expiry_date > issue_date OR expiry_date IS NULL");
                        });
                });

            modelBuilder.Entity("MediMind.Domain.Entities.QueueEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("queue_id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime?>("CalledTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("called_time");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("center_id");

                    b.Property<DateTime?>("ConsultationEndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consultation_end_time");

                    b.Property<DateTime?>("ConsultationStartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consultation_start_time");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("EstimatedWaitTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimated_wait_time_minutes");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<DateOnly>("QueueDate")
                        .HasColumnType("date")
                        .HasColumnName("queue_date");

                    b.Property<string>("QueueNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("queue_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_queue");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("i_x_queue_appointment_id");

                    b.HasIndex("CenterId", "Position")
                        .HasDatabaseName("i_x_queue_center_id_position");

                    b.HasIndex("CenterId", "QueueDate", "QueueNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_queue_center_id_queue_date_queue_number");

                    b.HasIndex("CenterId", "QueueDate", "Status")
                        .HasDatabaseName("i_x_queue_center_id_queue_date_status");

                    b.ToTable("queue", null, t =>
                        {
                            t.HasCheckConstraint("ck_estimated_wait", "estimated_wait_time_minutes >= 0");

                            t.HasCheckConstraint("ck_queue_position", "position > 0");
                        });
                });

            modelBuilder.Entity("MediMind.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("gender");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login");

                    b.Property<int>("OtpAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("otp_attempts");

                    b.Property<string>("OtpCode")
                        .HasColumnType("text")
                        .HasColumnName("otp_code");

                    b.Property<DateTime?>("OtpExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("otp_expires_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("profile_image_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("i_x_users_phone_number");

                    b.HasIndex("UserType", "Status")
                        .HasDatabaseName("i_x_users_user_type_status");

                    b.ToTable("users", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MediMind.Domain.Entities.VideoConsultation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("consultation_id");

                    b.Property<Guid>("AppointmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("appointment_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("room_id");

                    b.Property<DateTime?>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("VideoQuality")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("video_quality");

                    b.HasKey("Id")
                        .HasName("p_k_video_consultations");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasDatabaseName("i_x_video_consultations_appointment_id");

                    b.HasIndex("RoomId")
                        .IsUnique()
                        .HasDatabaseName("i_x_video_consultations_room_id");

                    b.ToTable("video_consultations", null, t =>
                        {
                            t.HasCheckConstraint("ck_duration_minutes_vc", "duration_minutes >= 0 OR duration_minutes IS NULL");
                        });
                });

            modelBuilder.Entity("MediMind.Domain.Entities.VideoConsultationParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uuid")
                        .HasColumnName("consultation_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_video_consultation_participants");

                    b.HasIndex("ConsultationId")
                        .HasDatabaseName("i_x_video_consultation_participants_consultation_id");

                    b.ToTable("video_consultation_participants", null, t =>
                        {
                            t.HasCheckConstraint("ck_left_after_joined", "left_at > joined_at OR left_at IS NULL");

                            t.HasCheckConstraint("ck_participant_identity", "patient_id IS NOT NULL OR doctor_id IS NOT NULL");
                        });
                });

            modelBuilder.Entity("MediMind.Domain.Entities.Doctor", b =>
                {
                    b.HasBaseType("MediMind.Domain.Entities.User");

                    b.PrimitiveCollection<List<string>>("LanguagesSpoken")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("languages_spoken");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("license_number");

                    b.Property<string>("Qualifications")
                        .HasColumnType("text")
                        .HasColumnName("qualifications");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialization");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_of_experience");

                    b.ToTable("doctor");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.HealthcareCenterAdmin", b =>
                {
                    b.HasBaseType("MediMind.Domain.Entities.User");

                    b.Property<Guid>("CenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("center_id");

                    b.Property<string>("Department")
                        .HasColumnType("text")
                        .HasColumnName("department");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasIndex("CenterId")
                        .HasDatabaseName("i_x_healthcare_center_admin_center_id");

                    b.ToTable("healthcare_center_admin");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.Patient", b =>
                {
                    b.HasBaseType("MediMind.Domain.Entities.User");

                    b.Property<string>("Allergies")
                        .HasColumnType("text")
                        .HasColumnName("allergies");

                    b.Property<int?>("BloodType")
                        .HasColumnType("integer")
                        .HasColumnName("blood_type");

                    b.PrimitiveCollection<List<string>>("ChronicConditions")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("chronic_conditions");

                    b.PrimitiveCollection<List<string>>("CurrentMedications")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("current_medications");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("text")
                        .HasColumnName("emergency_contact_name");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("emergency_contact_phone");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("text")
                        .HasColumnName("medical_history");

                    b.ToTable("patient");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("MediMind.Domain.Entities.HealthcareCenterAdmin", "ApprovedByAdmin")
                        .WithMany("ApprovedAppointments")
                        .HasForeignKey("ApprovedByAdminId")
                        .HasConstraintName("f_k_appointments__healthcare_center_admin_approved_by_admin_id");

                    b.HasOne("MediMind.Domain.Entities.HealthcareCenter", "Center")
                        .WithMany("Appointments")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_appointments_healthcare_centers_center_id");

                    b.HasOne("MediMind.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_appointments__doctor_doctor_id");

                    b.HasOne("MediMind.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_appointments__patient_patient_id");

                    b.Navigation("ApprovedByAdmin");

                    b.Navigation("Center");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.DoctorHealthcareCenter", b =>
                {
                    b.HasOne("MediMind.Domain.Entities.HealthcareCenter", "Center")
                        .WithMany("DoctorHealthcareCenters")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_doctor_healthcare_centers_healthcare_centers_center_id");

                    b.HasOne("MediMind.Domain.Entities.Doctor", "Doctor")
                        .WithMany("DoctorHealthcareCenters")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_doctor_healthcare_centers_doctor_doctor_id");

                    b.Navigation("Center");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.DoctorSchedule", b =>
                {
                    b.HasOne("MediMind.Domain.Entities.HealthcareCenter", "Center")
                        .WithMany("DoctorSchedules")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_doctor_schedules_healthcare_centers_center_id");

                    b.HasOne("MediMind.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_doctor_schedules_doctor_doctor_id");

                    b.Navigation("Center");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.HealthPrediction", b =>
                {
                    b.HasOne("MediMind.Domain.Entities.Patient", "Patient")
                        .WithMany("HealthPredictions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_health_predictions__patient_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.HealthPredictionRecord", b =>
                {
                    b.HasOne("MediMind.Domain.Entities.HealthPrediction", "Prediction")
                        .WithMany("PredictionRecords")
                        .HasForeignKey("PredictionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_health_prediction_records_health_predictions_prediction_id");

                    b.HasOne("MediMind.Domain.Entities.HealthRecord", "Record")
                        .WithMany()
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_health_prediction_records_health_records_record_id");

                    b.Navigation("Prediction");

                    b.Navigation("Record");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.HealthRecord", b =>
                {
                    b.HasOne("MediMind.Domain.Entities.Patient", "Patient")
                        .WithMany("HealthRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_health_records__patient_patient_id");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.Payment", b =>
                {
                    b.HasOne("MediMind.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Payments")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_payments_appointments_appointment_id");

                    b.HasOne("MediMind.Domain.Entities.Patient", "Patient")
                        .WithMany("Payments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_payments_patient_patient_id");

                    b.Navigation("Appointment");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("MediMind.Domain.Entities.Appointment", "Appointment")
                        .WithMany("Prescriptions")
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_prescriptions_appointments_appointment_id");

                    b.HasOne("MediMind.Domain.Entities.HealthcareCenter", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_prescriptions_healthcare_centers_center_id");

                    b.HasOne("MediMind.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Prescriptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_prescriptions_doctor_doctor_id");

                    b.HasOne("MediMind.Domain.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_prescriptions_patient_patient_id");

                    b.Navigation("Appointment");

                    b.Navigation("Center");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.QueueEntry", b =>
                {
                    b.HasOne("MediMind.Domain.Entities.Appointment", "Appointment")
                        .WithOne("QueueEntry")
                        .HasForeignKey("MediMind.Domain.Entities.QueueEntry", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_queue_appointments_appointment_id");

                    b.HasOne("MediMind.Domain.Entities.HealthcareCenter", "Center")
                        .WithMany("QueueEntries")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_queue_healthcare_centers_center_id");

                    b.Navigation("Appointment");

                    b.Navigation("Center");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.VideoConsultation", b =>
                {
                    b.HasOne("MediMind.Domain.Entities.Appointment", "Appointment")
                        .WithOne("VideoConsultation")
                        .HasForeignKey("MediMind.Domain.Entities.VideoConsultation", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_video_consultations_appointments_appointment_id");

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.VideoConsultationParticipant", b =>
                {
                    b.HasOne("MediMind.Domain.Entities.VideoConsultation", null)
                        .WithMany("Participants")
                        .HasForeignKey("ConsultationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_video_consultation_participants_video_consultations_consult~");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.Doctor", b =>
                {
                    b.HasOne("MediMind.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("MediMind.Domain.Entities.Doctor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediMind.Domain.Entities.HealthcareCenterAdmin", b =>
                {
                    b.HasOne("MediMind.Domain.Entities.HealthcareCenter", "Center")
                        .WithMany("Admins")
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("f_k_healthcare_center_admin_healthcare_centers_center_id");

                    b.HasOne("MediMind.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("MediMind.Domain.Entities.HealthcareCenterAdmin", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Center");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.Patient", b =>
                {
                    b.HasOne("MediMind.Domain.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("MediMind.Domain.Entities.Patient", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MediMind.Domain.Entities.Appointment", b =>
                {
                    b.Navigation("Payments");

                    b.Navigation("Prescriptions");

                    b.Navigation("QueueEntry");

                    b.Navigation("VideoConsultation");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.HealthPrediction", b =>
                {
                    b.Navigation("PredictionRecords");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.HealthcareCenter", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Appointments");

                    b.Navigation("DoctorHealthcareCenters");

                    b.Navigation("DoctorSchedules");

                    b.Navigation("QueueEntries");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.VideoConsultation", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DoctorHealthcareCenters");

                    b.Navigation("Prescriptions");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.HealthcareCenterAdmin", b =>
                {
                    b.Navigation("ApprovedAppointments");
                });

            modelBuilder.Entity("MediMind.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("HealthPredictions");

                    b.Navigation("HealthRecords");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
